name: hed_lines_remake
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"







dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  i18n_extension: ^4.2.0
  hive: ^2.2.2
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  equatable: ^2.0.3

  
  
  
  
  
  flutter_lints: ^1.0.0





flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/audio/
    - assets/images/svg/

  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceCodePro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceCodePro-Bold.ttf
          weight: 700
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
